#!/bin/sh

# set project home directory
Project_Home=~/qing_test
Project_Name=qing_test

# create a session
tmux has-session -t ${Project_Name}
if [ $? != 0 ]
then
  # create new session
  tmux new-session -s ${Project_Name} -c ${Project_Home} -n editor -d vim

  # split windows
  tmux split-window -h -p 35 -t ${Project_Name} -c ${Project_Home}

  # split windowss
  tmux split-window -v -t ${Project_Name} -c ${Project_Home}

  # create new window
  tmux new-window -c ~/ -n tmp -t ${Project_Name}

  # display window
  tmux select-window -t ${Project_Name}:1
  tmux select-pane -t ${Project_Name} -L
fi
tmux attach -t ${Project_Name}
