#!/bin/sh

# set project home directory
Project_Home='~/gitlab/cbt_store/'
Project_Name=cbt_store

# create a session
tmux has-session -t ${Project_Name}
if [ $? != 0 ]
then
  # create new session
  tmux new-session -s ${Project_Name} -n editor -d "cd ${Project_Home}&&vim ."

  # split windows
  #tmux split-window -h -p 35 -t ${Project_Name} -c ${Project_Home}

  # split windowss
  #tmux split-window -v -t ${Project_Name} -c ${Project_Home}

  # create new window
  tmux new-window -c ${Project_Home} -n console -t ${Project_Name} 'RAILS_ENV=development bundle exec rails c'

  # create new window
  tmux new-window -c ${Project_Home} -n runing -t ${Project_Name} 'RAILS_ENV=development bundle exec rails s' 

  # create new window
  tmux new-window -c ${Project_Home} -n tmp -t ${Project_Name} 'RAILS_ENV=development bundle exec rails s' 

  # display window
  tmux select-window -t ${Project_Name}:1
  tmux select-pane -t ${Project_Name} -L
fi
tmux attach -t ${Project_Name}
